from pathlib import Path
p=Path('simulation.html')
s=p.read_text()
# CSS
anchor='.analysis-legacy{display:none!important}'
css='''.offers-fit{width:calc(100% + 112px);margin:0 -56px -52px;padding:42px 56px 48px;background:linear-gradient(180deg,#d8dcdd,var(--silver));color:var(--blue)}.offers-fit h2{font-size:clamp(34px,4vw,52px);margin:0 0 8px}.offers-fit-lead{max-width:850px;color:#29445c;line-height:1.6;margin:0 0 26px}.offers-fit-table{display:grid;gap:1px;background:rgba(16,36,58,.14);border:1px solid rgba(16,36,58,.14);border-radius:18px;overflow:hidden}.offers-fit-row{display:grid;grid-template-columns:minmax(320px,1.8fr) repeat(3,minmax(120px,.55fr));background:rgba(242,238,229,.72)}.offers-fit-cell{padding:15px 18px;display:flex;align-items:center;border-left:1px solid rgba(16,36,58,.12)}.offers-fit-cell:first-child{border-left:0}.offers-fit-head{font-weight:850;justify-content:center;text-align:center;background:rgba(242,238,229,.9)}.offers-fit-head:first-child{justify-content:flex-start}.offers-fit-opt{display:block}.offers-fit-opt strong{display:block;font-size:14px}.offers-fit-opt small{display:block;color:#50677a;margin-top:4px}.offers-fit-mark{justify-content:center;font-size:20px;font-weight:900}.offers-fit-mark.yes{color:#8b6418}.offers-fit-mark.no{color:#71808c}.offers-fit-plans{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:18px}.offers-fit-plan{background:rgba(242,238,229,.78);border:1px solid rgba(16,36,58,.14);border-radius:16px;padding:18px;text-align:center}.offers-fit-plan h3{font-size:21px;margin:0 0 6px}.offers-fit-plan strong{font-size:22px}.offers-fit-plan.signature{background:linear-gradient(135deg,#d9aa45,#6d501b);color:var(--cream)}.offers-fit-plan.signature h3,.offers-fit-plan.signature strong{color:var(--cream)}@media(max-width:800px){.offers-fit{width:calc(100% + 44px);margin-left:-22px;margin-right:-22px;margin-bottom:-22px;padding:30px 22px}.offers-fit-row{grid-template-columns:minmax(190px,1.5fr) repeat(3,minmax(82px,.5fr));overflow:auto}.offers-fit-cell{padding:12px 9px;font-size:12px}.offers-fit-plans{grid-template-columns:1fr}}'''
if anchor not in s: raise SystemExit('css anchor')
s=s.replace(anchor,css+anchor,1)
# HTML before result actions
anchor='<div class="result-actions">'
html='''<section class="offers-fit" id="offersFitSection" hidden><h2>Les offres adéquates</h2><p class="offers-fit-lead">Voici les offres qui correspondent aux optimisations identifiées dans votre fonctionnement. Seuls les besoins qui vous concernent apparaissent ici.</p><div class="offers-fit-table" id="offersFitTable"></div><div class="offers-fit-plans" id="offersFitPlans"></div></section>\n'''
if anchor not in s: raise SystemExit('html anchor')
s=s.replace(anchor,html+anchor,1)
# renderer before showResult
anchor='function showResult(){'
js='''function renderOffersFit(r){const section=$('offersFitSection'),table=$('offersFitTable'),plans=$('offersFitPlans');if(!section||!table||!plans)return;const levels=r.optimizationLevels||{};const items=[...(levels.critical||[]),...(levels.structuring||[]),...(levels.advanced||[])];if(!items.length){section.hidden=true;return}const coverage=x=>{const p=x.priority||0;return{essentiel:p>=85,plus:p>=70,signature:true}};const level=x=>x.priority>=85?'Critique':x.priority>=70?'Structurante':'Avancée';const mark=v=>`<div class="offers-fit-cell offers-fit-mark ${v?'yes':'no'}">${v?'✓':'—'}</div>`;table.innerHTML=`<div class="offers-fit-row"><div class="offers-fit-cell offers-fit-head">Optimisations identifiées chez vous</div><div class="offers-fit-cell offers-fit-head">ESSENTIEL</div><div class="offers-fit-cell offers-fit-head">ESSENTIEL+</div><div class="offers-fit-cell offers-fit-head">SIGNATURE</div></div>`+items.map(x=>{const c=coverage(x);return `<div class="offers-fit-row"><div class="offers-fit-cell"><div class="offers-fit-opt"><strong>${x.text}</strong><small>${level(x)}</small></div></div>${mark(c.essentiel)}${mark(c.plus)}${mark(c.signature)}</div>`}).join('');plans.innerHTML=`<article class="offers-fit-plan"><h3>ESSENTIEL</h3><strong>2 500 € Net</strong><p>Pour sécuriser les priorités critiques identifiées.</p></article><article class="offers-fit-plan"><h3>ESSENTIEL+</h3><strong>4 000 € Net</strong><p>Pour traiter les priorités critiques et structurantes.</p></article><article class="offers-fit-plan signature"><h3>SIGNATURE</h3><strong>9 000 € Net</strong><p>Pour intégrer également les optimisations avancées.</p></article>`;section.hidden=false}\n'''
if anchor not in s: raise SystemExit('js anchor')
s=s.replace(anchor,js+anchor,1)
# call after analysis
needle='renderAnalysisSections(r);'
if needle not in s: raise SystemExit('call anchor')
s=s.replace(needle,needle+'renderOffersFit(r);',1)
p.write_text(s)
