from pathlib import Path
p=Path('simulation.html')
s=p.read_text()
s=s.replace("render('analysisOptimizationsSection','analysisOptimizations',r.axes);","render('analysisOptimizationsSection','analysisOptimizations',(r.improvements||[]).map(x=>({text:x,why:''})));",1)
old="function showResult(){const r=buildResult();$('resultProfileTitle').textContent='Votre simulation';$('resultProfileText').textContent='';$('resultProfileText').style.display='none';renderPhaseSummary();renderAnalysisSections(r);const strengthText=r.strengths.length?r.strengths.map(x=>`<strong>${x.text}</strong> ${x.why}`).join(' '):'Votre fonctionnement ne présente pas encore de point fort suffisamment net pour être isolé, mais il reste lisible et peut être amélioré sans tout reconstruire.';const weaknessText=r.weaknesses.length?r.weaknesses.map(x=>`<strong>${x.text}</strong> ${x.why}`).join(' '):'Aucun point faible majeur ne ressort de vos réponses : l’enjeu est surtout de conserver ce qui fonctionne déjà.';$('resultNarrative').innerHTML=`<strong>Ce qui fonctionne déjà.</strong> ${strengthText}<br><br><strong>Les points à surveiller.</strong> ${weaknessText}`;const axes=r.improvements.length?r.improvements.map((x,i)=>`${i+1}. ${x}`).join(' '):'Conserver votre organisation actuelle et n’ajouter que les sécurités réellement utiles.';$('resultSolution').innerHTML=`<strong>Axes d’amélioration possibles.</strong> ${axes}`;if(r.advancedEligible){$('resultOfferText').innerHTML=`En choisissant de traiter uniquement les frictions prioritaires et de garder une optimisation mesurée du workflow, le périmètre peut rester autour d’<strong class=\"offer-inline\">ESSENTIEL+</strong>. Si vous souhaitez aller plus loin — davantage d’orchestration entre les parcours, d’automatismes et de sécurisation des étapes — le projet peut évoluer vers <strong class=\"offer-inline\">SIGNATURE</strong>. L’objectif est de choisir le niveau d’optimisation qui a réellement du sens pour votre activité, pas d’ajouter de la complexité pour elle-même.`}else{$('resultOfferText').innerHTML=`Au vu de votre fonctionnement, une optimisation ciblée semble suffisante. Le périmètre se rapproche d’<strong class=\"offer-inline\">ESSENTIEL+</strong> : corriger les principales frictions sans transformer inutilement ce qui fonctionne déjà. Aller jusqu’à Signature ne paraît pas justifié à ce stade.`}const crmNote=r.crm?' Votre utilisation actuelle d’un CRM pourra naturellement être prise en compte dans cette réflexion.':'';$('offerNote').textContent='Cette orientation reste indicative. Le périmètre final dépendra des améliorations que vous choisirez réellement de retenir et des outils à connecter.'+crmNote;renderDiagnosticTree();$('diagnosticDetail').hidden=true;$('diagnosticToggle').setAttribute('aria-expanded','false');$('questions').classList.remove('active');$('result').classList.add('active');window.scrollTo({top:0,behavior:'smooth'});saveDebugSession()}"
new="function showResult(){const r=buildResult();$('resultProfileTitle').textContent='Votre simulation';$('resultProfileText').textContent='';$('resultProfileText').style.display='none';renderPhaseSummary();renderAnalysisSections(r);renderDiagnosticTree();$('diagnosticDetail').hidden=true;$('diagnosticToggle').setAttribute('aria-expanded','false');$('questions').classList.remove('active');$('result').classList.add('active');window.scrollTo({top:0,behavior:'smooth'});saveDebugSession()}"
if old not in s:
    raise SystemExit('showResult target not found')
s=s.replace(old,new,1)
p.write_text(s)
