from pathlib import Path
p=Path('simulation.html')
s=p.read_text()
old='.phase-summary-card{border:1px solid rgba(16,36,58,.18);border-radius:18px;padding:20px 24px;background:var(--silver);color:var(--blue);display:grid;grid-template-columns:minmax(170px,220px) minmax(0,1fr);column-gap:28px;align-items:start}.phase-summary-card .summary-phase{display:block;color:#9b6c18;font-size:11px;font-weight:850;letter-spacing:1.2px;text-transform:uppercase;margin-bottom:5px;grid-column:1}.phase-summary-card h3{font-size:22px;margin:0;grid-column:1}.phase-summary-card .phase-summary-row{grid-column:2;display:grid;grid-template-columns:minmax(150px,220px) minmax(0,1fr);column-gap:18px;align-items:start;padding:8px 0;border-top:1px solid rgba(16,36,58,.12)}.phase-summary-card .phase-summary-row:nth-of-type(1){border-top:0;padding-top:0}.phase-summary-row h4{font-size:12px;line-height:1.35;margin:0;color:#50677a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-weight:800}.phase-summary-row ul{margin:0;padding-left:18px}.phase-summary-row li{font-size:13px;line-height:1.4;margin:2px 0}'
new='.phase-summary-card{border:1px solid rgba(16,36,58,.18);border-radius:18px;padding:20px 24px;background:var(--silver);color:var(--blue);display:grid;grid-template-columns:minmax(170px,220px) minmax(0,1fr);column-gap:28px;align-items:start}.phase-summary-head{grid-column:1;grid-row:1}.phase-summary-card .summary-phase{display:block;color:#9b6c18;font-size:11px;font-weight:850;letter-spacing:1.2px;text-transform:uppercase;margin-bottom:5px}.phase-summary-card h3{font-size:22px;margin:0}.phase-summary-body{grid-column:2;grid-row:1;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0}.phase-summary-row{min-width:0;padding:2px 18px 10px;border-left:1px solid rgba(16,36,58,.12)}.phase-summary-row h4{font-size:12px;line-height:1.35;margin:0 0 7px;color:#29445c;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-weight:850}.phase-summary-row ul{margin:0;padding-left:18px}.phase-summary-row li{font-size:13px;line-height:1.4;margin:2px 0}'
if old not in s: raise SystemExit('css target not found')
s=s.replace(old,new,1)
old='function renderPhaseSummary(){const root=$(\'phaseSummary\');if(!root)return;const phases=[{phase:1,title:\'Parcours prospect\'},{phase:2,title:\'Qualification en client\'},{phase:3,title:\'Parcours client\'},{phase:4,title:\'Fidélisation client\'}];root.innerHTML=phases.map(p=>{const rows=phaseAnswers(p.phase).map(a=>`<div class="phase-summary-row"><h4>${a.label}</h4><ul>${a.values.map(v=>`<li>${v}</li>`).join(\'\')}</ul></div>`).join(\'\');return `<article class="phase-summary-card"><span class="summary-phase">Phase ${p.phase}</span><h3>${p.title}</h3>${rows}</article>`}).join(\'\')}'
new='function renderPhaseSummary(){const root=$(\'phaseSummary\');if(!root)return;const phases=[{phase:1,title:\'Parcours prospect\'},{phase:2,title:\'Qualification en client\'},{phase:3,title:\'Parcours client\'},{phase:4,title:\'Fidélisation client\'}];root.innerHTML=phases.map(p=>{const rows=phaseAnswers(p.phase).map(a=>`<div class="phase-summary-row"><h4>${a.label}</h4><ul>${a.values.map(v=>`<li>${v}</li>`).join(\'\')}</ul></div>`).join(\'\');return `<article class="phase-summary-card"><div class="phase-summary-head"><span class="summary-phase">Phase ${p.phase}</span><h3>${p.title}</h3></div><div class="phase-summary-body">${rows}</div></article>`}).join(\'\')}'
if old not in s: raise SystemExit('renderer target not found')
s=s.replace(old,new,1)
old='@media(max-width:1100px){.grid{grid-template-columns:1fr}.map-card{position:relative;top:auto}.diagnostic-tree{grid-template-columns:repeat(2,minmax(0,1fr))}.phase-summary{grid-template-columns:1fr}.phase-summary-card{grid-template-columns:1fr}.phase-summary-card .summary-phase,.phase-summary-card h3,.phase-summary-card .phase-summary-row{grid-column:1}.phase-summary-card h3{margin-bottom:12px}.phase-summary-card .phase-summary-row{grid-template-columns:minmax(150px,220px) minmax(0,1fr)}}'
new='@media(max-width:1100px){.grid{grid-template-columns:1fr}.map-card{position:relative;top:auto}.diagnostic-tree{grid-template-columns:repeat(2,minmax(0,1fr))}.phase-summary{grid-template-columns:1fr}.phase-summary-card{grid-template-columns:minmax(150px,190px) minmax(0,1fr)}.phase-summary-body{grid-template-columns:repeat(3,minmax(0,1fr))}}'
if old not in s: raise SystemExit('1100 target not found')
s=s.replace(old,new,1)
old='@media(max-width:600px){.question,.map-card,.result-card{padding:22px}.diagnostic-tree,.phase-summary{grid-template-columns:1fr}.phase-summary-card{padding:18px}.phase-summary-card .phase-summary-row{grid-template-columns:1fr}.phase-summary-row h4{margin-bottom:5px}.diagnostic-toggle'
new='@media(max-width:600px){.question,.map-card,.result-card{padding:22px}.diagnostic-tree,.phase-summary{grid-template-columns:1fr}.phase-summary-card{padding:18px;grid-template-columns:1fr}.phase-summary-head,.phase-summary-body{grid-column:1;grid-row:auto}.phase-summary-head{margin-bottom:14px}.phase-summary-body{grid-template-columns:1fr}.phase-summary-row{border-left:0;border-top:1px solid rgba(16,36,58,.12);padding:10px 0}.phase-summary-row:first-child{border-top:0;padding-top:0}.phase-summary-row h4{margin-bottom:5px}.diagnostic-toggle'
if old not in s: raise SystemExit('mobile target not found')
s=s.replace(old,new,1)
p.write_text(s)
