from pathlib import Path
p=Path('simulation.html')
s=p.read_text()
old='.result-layout{display:block}.result-card{width:100%;background:var(--cream);color:var(--blue);padding:52px 56px}.result-card>h2{font-size:clamp(38px,5vw,62px);line-height:1.02;margin:0 0 18px;max-width:980px}.result-lead{font-size:18px;line-height:1.65;color:#29445c;max-width:1080px;margin:0}.phase-summary{display:grid;grid-template-columns:1fr;gap:16px;margin-top:32px;padding:18px;background:var(--blue);border-radius:22px}.phase-summary-card{border:1px solid rgba(16,36,58,.18);border-radius:18px;padding:20px 24px;background:var(--silver);color:var(--blue);display:grid;grid-template-columns:minmax(170px,220px) minmax(0,1fr);column-gap:28px;align-items:start}.phase-summary-head{grid-column:1;grid-row:1}.phase-summary-card .summary-phase{display:block;color:#9b6c18;font-size:11px;font-weight:850;letter-spacing:1.2px;text-transform:uppercase;margin-bottom:5px}.phase-summary-card h3{font-size:22px;margin:0}.phase-summary-body{grid-column:2;grid-row:1;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0}.phase-summary-row{min-width:0;padding:2px 18px 10px;border-left:1px solid rgba(16,36,58,.12)}'
new='.result-layout{display:block}.result-card{width:100%;background:var(--blue);color:var(--cream);padding:52px 56px}.result-card>h2{font-size:clamp(38px,5vw,62px);line-height:1.02;margin:0 0 18px;max-width:980px;color:var(--cream)}.result-lead{font-size:18px;line-height:1.65;color:#c7d0d5;max-width:1080px;margin:0}.phase-summary{display:grid;grid-template-columns:1fr;gap:14px;margin-top:32px;padding:0;background:transparent;border-radius:22px}.phase-summary-card{border:1px solid rgba(231,178,74,.35);border-radius:18px;padding:0;background:transparent;color:var(--blue);display:grid;grid-template-columns:minmax(220px,280px) minmax(0,1fr);column-gap:0;align-items:stretch;overflow:hidden;box-shadow:0 10px 28px rgba(4,12,20,.16)}.phase-summary-head{grid-column:1;grid-row:1;background:linear-gradient(180deg,#f1c86f,var(--gold));padding:22px 24px;border-right:4px solid var(--blue);display:flex;flex-direction:column;justify-content:center}.phase-summary-card .summary-phase{display:block;color:#6f4b0d;font-size:11px;font-weight:900;letter-spacing:1.2px;text-transform:uppercase;margin-bottom:7px}.phase-summary-card h3{font-size:24px;line-height:1.05;margin:0;color:var(--blue)}.phase-summary-body{grid-column:2;grid-row:1;background:linear-gradient(180deg,#d8dcdd,var(--silver));display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0;padding:18px 10px}.phase-summary-row{min-width:0;padding:4px 18px 10px;border-left:1px solid rgba(16,36,58,.14)}'
if old not in s: raise SystemExit('main summary css target not found')
s=s.replace(old,new,1)
old='@media(max-width:1100px){.grid{grid-template-columns:1fr}.map-card{position:relative;top:auto}.diagnostic-tree{grid-template-columns:repeat(2,minmax(0,1fr))}.phase-summary{grid-template-columns:1fr}.phase-summary-card{grid-template-columns:minmax(150px,190px) minmax(0,1fr)}.phase-summary-body{grid-template-columns:repeat(3,minmax(0,1fr))}}'
new='@media(max-width:1100px){.grid{grid-template-columns:1fr}.map-card{position:relative;top:auto}.diagnostic-tree{grid-template-columns:repeat(2,minmax(0,1fr))}.phase-summary{grid-template-columns:1fr}.phase-summary-card{grid-template-columns:minmax(180px,220px) minmax(0,1fr)}.phase-summary-body{grid-template-columns:repeat(3,minmax(0,1fr))}}'
if old not in s: raise SystemExit('tablet target not found')
s=s.replace(old,new,1)
old='@media(max-width:600px){.question,.map-card,.result-card{padding:22px}.diagnostic-tree,.phase-summary{grid-template-columns:1fr}.phase-summary-card{padding:18px;grid-template-columns:1fr}.phase-summary-head,.phase-summary-body{grid-column:1;grid-row:auto}.phase-summary-head{margin-bottom:14px}.phase-summary-body{grid-template-columns:1fr}.phase-summary-row{border-left:0;border-top:1px solid rgba(16,36,58,.12);padding:10px 0}.phase-summary-row:first-child{border-top:0;padding-top:0}.phase-summary-row h4{margin-bottom:5px}.diagnostic-toggle'
new='@media(max-width:600px){.question,.map-card,.result-card{padding:22px}.diagnostic-tree,.phase-summary{grid-template-columns:1fr}.phase-summary-card{grid-template-columns:1fr}.phase-summary-head,.phase-summary-body{grid-column:1;grid-row:auto}.phase-summary-head{margin:0;border-right:0;border-bottom:4px solid var(--blue);padding:18px}.phase-summary-body{grid-template-columns:1fr;padding:14px 18px}.phase-summary-row{border-left:0;border-top:1px solid rgba(16,36,58,.12);padding:10px 0}.phase-summary-row:first-child{border-top:0;padding-top:0}.phase-summary-row h4{margin-bottom:5px}.diagnostic-toggle'
if old not in s: raise SystemExit('mobile target not found')
s=s.replace(old,new,1)
# Keep analysis below readable on the now-blue result card
s=s.replace('.result-flow{max-width:1120px;margin-top:30px;padding-top:28px;border-top:1px solid rgba(16,36,58,.16)}.result-flow p{font-size:17px;line-height:1.75;margin:0 0 22px}', '.result-flow{max-width:1120px;margin-top:30px;padding:28px 30px 8px;border-top:0;border-radius:18px;background:var(--cream);color:var(--blue)}.result-flow p{font-size:17px;line-height:1.75;margin:0 0 22px}')
s=s.replace('.offer-note{color:#50677a!important;font-size:14px!important}', '.offer-note{color:#50677a!important;font-size:14px!important}')
p.write_text(s)
