from pathlib import Path

p = Path('simulation.html')
s = p.read_text(encoding='utf-8')
needle = '.offers-fit-plan.recommended{'
css = '''.offers-fit-cell:not(.offers-fit-opt) .fit-check{display:grid;place-items:center;width:34px;height:34px;margin:auto;border-radius:50%;background:var(--blue);color:var(--cream);font-size:21px;font-weight:950;line-height:1;box-shadow:0 0 0 5px rgba(242,238,229,.72),0 4px 10px rgba(16,36,58,.18)}\n.offers-fit-cell:not(.offers-fit-opt) .fit-dash{display:grid;place-items:center;width:34px;height:34px;margin:auto;border-radius:50%;background:rgba(216,220,221,.92);color:#607487;font-size:20px;font-weight:900;line-height:1}\n'''
if css.strip() not in s:
    i = s.find(needle)
    if i < 0:
        raise SystemExit('CSS anchor not found')
    s = s[:i] + css + s[i:]
# Add classes to the status spans generated by renderOffersFit without changing coverage logic.
s = s.replace("`<span>${covered?'✓':'—'}</span>`", "`<span class=\"${covered?'fit-check':'fit-dash'}\">${covered?'✓':'—'}</span>`")
p.write_text(s, encoding='utf-8')
